In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.1'

In [3]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000015DB8519E40>, toplevel='numpy')>

In [5]:
a = [1,2,3,4]
b = [5,6,7,8]

In [7]:
a_array = np.array(a)
b_array = np.array(b)
a_array

array([1, 2, 3, 4])

In [8]:
print(a_array+ b_array)
print(a_array* b_array)

[ 6  8 10 12]
[ 5 12 21 32]


In [9]:
v = np.array([1,2,3,4,5])
v.shape

(5,)

In [10]:
n = np.array([[1,2,3,4],[5,6,7,8]])
n.shape


(2, 4)

In [11]:
type(v), type(n)

(numpy.ndarray, numpy.ndarray)

In [12]:
n.size

8

In [29]:
satu = np.array([1,2,3,4,5,6,7])
dua = np.array([[1,2,3],[4,5,6],[7,8,9]])
tiga = np.array([[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [9,10,11,12]],

                [[13,14,15,16],
                [1,2,3,4],
                [5,6,7,8],
                [5,6,7,8]],

                [[9,10,11,12],
                [13,14,15,16],
                [17,18,19,20],
                [17,18,19,20]],

                [[9,10,11,12],
                [13,14,15,16],
                [17,18,19,20],
                [17,18,19,20]]]
                )
satu.shape



(7,)

In [18]:
dua.shape

(3, 3)

In [30]:
tiga.shape

(4, 4, 4)

In [32]:
tiga[1][:][0]

array([13, 14, 15, 16])

In [33]:
ones = np.ones((7,7), dtype= int)
ones


array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [34]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
xy = np.arange(10,30,2)
xy

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [39]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])