In [62]:
import numpy as np

In [63]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.append(my_arr,[10,11,12], axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
a = np.array([[9,2,8],[5,9,8]])
b = np.array([[1,2,8],[5,7,8]])
np.concatenate((a,b), axis =1)

array([[9, 2, 8, 1, 2, 8],
       [5, 9, 8, 5, 7, 8]])

In [66]:
x=np.sort(a)
print(x)

[[2 8 9]
 [5 8 9]]


In [67]:
my_arr[::-1].sort()
print(my_arr)


[9 8 7 6 5 4 3 2 1 0]


In [68]:
np.delete(a,1,axis = 0)

array([[9, 2, 8]])

In [69]:
np.delete(b,0, axis=1)

array([[2, 8],
       [7, 8]])

In [70]:
array1 = np.zeros((3,4,5))
array1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [71]:
array1.size

60

In [72]:
array1.shape

(3, 4, 5)

In [73]:
array1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [74]:
array2 =  np.zeros((3,4))
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
array2.reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
ex = np.arange(2,11)
ex= ex.reshape(3,3)
ex


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [77]:
ex2 = np.array([[0,1,3],[5,7,9]])
ex3 = np.array([[0,2,4],[6,8,10]])
np.concatenate((ex2,ex3), axis =1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [78]:
my_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [79]:
my_arr1 = a[np.newaxis, :]
my_arr1

array([[[9, 2, 8],
        [5, 9, 8]]])

In [80]:
my_arr2 = a[ : ,np.newaxis]
my_arr2

array([[[9, 2, 8]],

       [[5, 9, 8]]])

In [81]:
my_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [82]:
c = my_arr[(my_arr > 2) & (my_arr <11)]
print(c)

[9 8 7 6 5 4 3]


In [83]:
d = my_arr[(my_arr > 4) | (my_arr==11)]
print(d)

[9 8 7 6 5]


In [84]:
aq = np.arange(6)
aq

array([0, 1, 2, 3, 4, 5])

In [91]:
aq[4]=11
aq

array([ 0,  1,  2,  3, 11,  5])

In [88]:
aq = np.arange(6)
aq1 =aq.reshape(2,3)
aq2 = aq1.reshape(3,2)
aq2.shape

(2, 3)

In [90]:
aq2 = aq1.reshape(3,2)
aq2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [93]:
az = np.zeros((3,3))
az1 = az[az%2==1]
az

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])